# permissions for end users to view policypublickeys.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: policypublickey-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-init
    app.kubernetes.io/part-of: kubebuilder-init
    app.kubernetes.io/managed-by: kustomize
  name: policypublickey-viewer-role
rules:
- apiGroups:
  - witness.testifysec.com
  resources:
  - policypublickeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - witness.testifysec.com
  resources:
  - policypublickeys/status
  verbs:
  - get
